version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - default-network
    volumes:
      - mariadb-volume:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    networks:
      - default-network
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - default-network
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/wassim/data/wordpress
      o: bind
  mariadb-volume:
    driver: local
    driver_opts:
      type: volume
      device: /home/wassim/data/db
      o: bind

networks:
  default-network:

